version: '3'
services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 3000:3000
  backend:
    build: ./backend
    container_name: backend
    ports:
      - 3001:3001    
    restart: 'always'