version: '3.9'

services:
  client-management-api:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - 3001:3001

  client-management-web:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
