version: '3.9'
services:
  frontend:
    build: ./frontend
    container_name: app_frontend
    ports:
      - 3000:3000
    platform: linux/x86_64
  backend:
    build: ./backend
    container_name: app_backend
    ports:
      - 3001:3001
    platform: linux/x86_64
    restart: 'always'
