version: '3'

services:
  api:
    build: .
    container_name: backend_api
    ports:
      - 3001:3001
    working_dir: /app
    volumes:
      - .:/app
    command: dev
    env_file:
      - .env
    depends_on:
      - database

  database:
    image: mysql:8
    container_name: backend_database
    ports:
      - 3306:3306
    env_file:
      - .env

