FROM node:16-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

ENV DATABASE_URL=file:./dev-test.db

RUN npx prisma generate --schema src/db/prisma/schema.prisma

RUN npx prisma migrate dev

CMD [ "npm", "start" ]
