Resources:
  ApiRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Sls_ApiRole_${self:service}_${opt:stage}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: 'sts:AssumeRole'
            Principal:
              Service: 'lambda.amazonaws.com'
      Policies:
        - PolicyName: Sls_ApiPolicy_${self:service}_${opt:stage}
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
